export const typeColors: { [key: string]: string } = {
  normal: "gray",
  fire: "red",
  water: "blue",
  grass: "green",
  electric: "yellow",
  ice: "cyan",
  fighting: "orange",
  poison: "purple",
  ground: "brown",
  flying: "teal",
  psychic: "pink",
  bug: "lime",
  rock: "beige",
  ghost: "indigo",
  dragon: "purple",
  dark: "blackAlpha",
  steel: "gray",
  fairy: "pink",
};
